### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by doublefox1981** [xjdrew/levent#18]
http://xjdrew.github.io/blog/2014/08/28/compile-levent/
这个链接已经不能打开了

**Comment by xjdrew** [comment]
修改了一下域名绑定：

http://xjdrew.github.io/blog/2014/08/28/compile-levent

现在可以了

**Comment by doublefox1981** [comment]
我访问这个地址仍然是404

**Comment by doublefox1981** [comment]
可能是我dns缓存的问题，清理后正常了，多谢。
