### ISSUE TITLE
macos 上connnet 成功情况下出现错误

### ISSUE THREAD

**Issue by samuelyao314** [xjdrew/levent#24]
test_socket.lua ， 我的环境下测试，老是失败。最后发现client 连接成功也会返回错误码 56。看文档是 EISCONN。我的代码如下。 修改了IP和端口

function client()
    local sock, errcode = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    assert(sock, errcode)
    print("begin connect:", sock:fileno())
    -- assert(sock:connect("127.0.0.1", 12345)
    local ok, err = sock:connect("127.0.0.1", 12345)
    print("connect", ok, err)
    sock:sendall(test_data)
    sock:close()
end

执行过程

~/Documents/workspace/levent$ lua tests/test_socket.lua 
begin accept:	5
begin connect:	6
connect	false	56
recv:	hello

**Comment by xjdrew** [comment]
#27 现在应该兼容了
