### ISSUE TITLE
不兼容lua5.3呢

### ISSUE THREAD

**Issue by xiuzhifu** [xjdrew/levent#6]
我去。看见blog写得5.2.3以上版本，特地下了5.3.0，想不用struct，报lua: error loading module 'levent.socket.c' from file './levent.so':
	dlopen(./levent.so, 6): Symbol not found: _luaL_checkint
  Referenced from: ./levent.so
  Expected in: flat namespace
看文档luaL_checkint 已经删了呢，╮(╯▽╰)╭

**Comment by xjdrew** [comment]
不好意思，还没兼容5.3；
5.3改动挺大的，等有空兼容一下^_^

**Comment by xjdrew** [comment]
支持lua5.3了。
